routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)

from werkzeug.utils import secure_filename
from models.user import User
from config import user_file_director
import os
from routes import *

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/logout")
def log_out():
    u = current_user()
    if u is None:
        return redirect(url_for(".index"))
    session.pop("user_id")
    return redirect(url_for(".index"))


@main.route("/")
def index():
    u = current_user()
    # print(123)
    # log(123333)
    # logger.debug('just do it')
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        # print('session before', session)
        session['user_id'] = u.id
        # print('session after', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# @main.route('/profile')
# def profile():
#     u = current_user()
#     if u is None:
#         return redirect(url_for('.index'))
#     else:
#         return render_template('profile.html', user=u)


def allow_file(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_file_type
    return suffix in accept_user_file_type


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".profile"))

    if 'file' not in request.files:
        # return redirect(request.url)
        abort(500)

    file = request.files['file']
    if file.filename == '':
        abort(500)
        # return redirect(url_for(".profile"))

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))  # 路径拼接
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    if filename is None:
        return ''
    return send_from_directory(user_file_director, filename)


@main.route('/setting')
def setting():
    # print(2333)
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('setting.html', user=u)


@main.route('/setpass', methods=["POST"])
def setpass():
    u = current_user()
    oldpass = request.form.get('old_pass', '')
    if u is not None and u.password == u.salted_password(oldpass):
        pwd = request.form.get('new_pass')
        u.password = u.salted_password(pwd)
        u.save()
        return redirect(url_for('.setting'))
    else:
        abort(403)

routes/mail.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
from models.mail import Mail


main = Blueprint('mail', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    mail = Mail.new(form)
    # 为了安全
    mail.set_sender(current_user().id)
    mail.set_receiver(mail.receiver_name)
    return redirect(url_for(".index"))


@main.route("/", methods=["GET"])
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    send_mail = Mail.find_all(sender_id=u.id)
    received_mail = Mail.find_all(receiver_id=u.id)

    return render_template("mail/index.html", sends=send_mail, receives=received_mail)


@main.route("/view/<int:id>")
def view(id):
    mail = Mail.find(id)
    # 不是你自己手法的，你肯定不能看
    # 不是收的人，那你看了也不会变成已读
    u = current_user()
    if current_user().id == mail.receiver_id:
        mail.mark_read()
    if current_user().id in [mail.receiver_id, mail.sender_id]:
        return render_template("mail/detail.html", mail=mail, user=u)
    else:
        return redirect(url_for(".index"))


@main.route('/<username>')
def setting(username):
    u = current_user()
    return render_template("mail/setting.html", user=u)

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply
from models.topic import Topic
from models.topic import User


main = Blueprint('user', __name__)


@main.route("/<username>")
def detail(username):
    # u = current_user()
    u = User.find_by(username=username)
    ts = Topic.find_all(user_id=u.id)
    tss = []
    rs = Reply.find_all(user_id=u.id)
    for r in rs:
        t = Topic.find_by(id=r.topic_id)
        if t is not None and t.user_id != u.id:
            tss.append(t)
    return render_template("user/detail.html", user=u, ts=ts, tss=tss)


@main.route('/update', methods=['POST'])
def update():
    u = current_user()
    form = request.form
    u.update(form)
    return redirect(url_for('index.setting'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base.html</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% block navbar %}
<!-- navbar -->
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href='/'>

                <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg"/>

            </a>

            <form id='search_form' class='navbar-search' action="/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href='{{url_for('topic.index')}}'>首页</a></li>
                <li><a href='{{url_for('mail.index')}}'>站内私信</a></li>
                <!--<li><a href='{{url_for('topic.index')}}'>关于</a></li>-->
                <li><a href={{ url_for('index.setting') }}>设置</a></li>
                <li><a href='/logout'>退出</a></li>

            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>q
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
    </div>
</div>
{% endblock %}
<div id="main">
    {% block sidebar %}
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href={{ url_for('user.detail', username=user.username) }}>
                        <img src={{ url_for('index.uploads', filename=user.user_image, v=3, s=120) }}>
                        </a>
                        <span class="user_name"><a class="dark" href={{ url_for('user.detail', username=user.username) }}>{{ user.username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.note }}
                        </span>
                    </div>
                </div>
            </div>
            </div>
            <div class="panel">
                    <div class="inner">
                        <a href="/topic/new" class="create_topic_btn">
                            <span class="span-success">发布话题</span>
                        </a>
                    </div>
                </div>
        </div>

    {% endblock %}

    {% block content %}
    {% endblock %}
</div>

{% block footer %}
<div id="footer">
    <div id="footer_main">
        <div class="links">
            <a class="dark" href="/rss">RSS</a>
            |
            <a class="dark" href="https://github.com/yiyangyu/bbs/">源码地址</a>
        </div>

        <div class="col_fade">

            <p>CNode 社区为国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究。</p>
            <p>服务器赞助商为
                <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo"
                   target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
                    <img src="//dn-cnode.qbox.me/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
                </a>
                ，存储赞助商为
                <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink"
                   data-label="qiniu_bottom">
                    <img src="//dn-cnode.qbox.me/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
                </a>
                ，由<a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="sponsor_outlink"
                     data-label="alinode_bottom">
                    <img src="//dn-cnode.qbox.me/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode"
                         height="54px" width="166px">
                </a>提供应用性能服务。
            </p>
            <p>新手搭建 Node.js 服务器，推荐使用无需备案的 <a href="https://www.digitalocean.com/?refcode=eba02656eeb3">DigitalOcean(https://www.digitalocean.com/)</a>
            </p>
        </div>


    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="password" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="password" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        {{ user.id }}
    </div>
    <div>
        {{ user.name }}
    </div>
    <div>
        {{ user.password }}
    </div>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form method=post action={{ url_for(".add_img") }} enctype=multipart/form-data>
        <input type=file name=file>
        <input type=submit value=Upload>
    </form>

</body>
</html>

templates/setting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>setting</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    {% block content %}
    <div id="content">
    <div class='panel'>
    <div class='header'>
      <ul class='breadcrumb'>
        <li><a href="{{url_for('topic.index')}}">主页</a><span class='divider'>/</span></li>
        <li class='active'>设置</li>
      </ul>
    </div>
    <div class='inner'>


      <form id='setting_form' class='form-horizontal' action={{ url_for('user.update') }} method='post'>
        <div class='control-group'>
          <label class='control-label' for='name'>用户名</label>

          <div class='controls'>
            <input class='input-xlarge readonly' id='name' name='name' size='30' type='text' readonly='true'
                   value={{ user.username }} />
          </div>
        </div>
        <div class='control-group'>
          <label class='control-label' for='email'>电子邮件</label>

          <div class='controls'>
            <input class='input-xlarge' id='email' name='email' size='30' type='text'
                    value='{{ user.email }}'/>

          </div>
        </div>
        <!--<div class='control-group'>-->
          <!--<label class='control-label' for='url'>个人网站</label>-->

          <!--<div class='controls'>-->
            <!--<input class='input-xlarge' id='url' name='url' size='30' type='text' value=""/>-->
          <!--</div>-->
        <!--</div>-->
        <div class='control-group'>
          <label class='control-label' for='location'>所在地点</label>

          <div class='controls'>
            <input class='input-xlarge' id='location' name='location' size='30' type='text'
                   value='{{ user.location }}'/>
          </div>
        </div>

        <!--<div class='control-group'>-->
          <!--<label class='control-label' for='weibo'>微博</label>-->

          <!--<div class='controls'>-->
            <!--<input class='input-xlarge' id='weibo' name='weibo' size='30' type='text' value=""-->
                   <!--placeholder="e.g. http://weibo.com/cnodejs"/>-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class='control-group'>-->
          <!--<label class='control-label' for='github'>GitHub</label>-->

          <!--<div class='controls'>-->
            <!--<input class='input-xlarge' id='github' name='github' size='30' type='text'-->
                   <!--value="@yiyangyu" placeholder="@username" readonly="readonly" />-->
            <!--<p>请通过 GitHub 登陆 CNode 来修改此处</p>-->
          <!--</div>-->
        <!--</div>-->
        <div class='control-group'>
          <label class='control-label' for='note'>个性签名</label>

          <div class='controls'>
            <textarea class='input-xlarge' id='note' name='note' size='30'>{{ user.note }}</textarea>
          </div>
        </div>
        <!--<input type='hidden' id='action' name='action' value='change_setting'/>-->
        <!--<input type='hidden' name='_csrf' value='nDXS2HTc-XpQxx2dK3Da8tzQgSWSm52Zg0zY'/>-->

        <div class='form-actions'>
          <input type='submit' class='span-primary submit_btn' data-loading-text="保存中.." value='保存设置'/>
        </div>
      </form>
    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>更改密码</span>
    </div>
    <div class='inner'>
      <form id='change_pass_form' class='form-horizontal' action='/setpass' method='post'>
        <div class='control-group'>
          <label class='control-label' for='old_pass'>当前密码</label>

          <div class='controls'>
            <input class='input-xlarge' type='password' id='old_pass' name='old_pass' size='30'/>
          </div>
        </div>
        <div class='control-group'>
          <label class='control-label' for='new_pass'>新密码</label>

          <div class='controls'>
            <input class='input-xlarge' type='password' id='new_pass' name='new_pass' size='30'/>
          </div>
        </div>
        <!--<input type='hidden' id='action' name='action' value='change_password'/>-->
        <!--<input type='hidden' name='_csrf' value='nDXS2HTc-XpQxx2dK3Da8tzQgSWSm52Zg0zY'/>-->

        <div class='form-actions'>
          <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.." value='更改密码'/>
        </div>
      </form>
    </div>
  </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">更改头像</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="/addimg" method="post" enctype="multipart/form-data">
                    <div class="control-group">
                        <div class="image-change control-label">
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="control-label" id="image-change">
                            <img src={{ url_for('index.uploads', filename=user.user_image, v=3, s=120) }}>
                        </div>

                        <div class="controls">
                            <div class="form-actions">
                                <input type="file" name="file">
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                        </div>
                    </div>
                </form>
            </div>
        </div>

</div>
    {% endblock %}
</div>
</body>
</html>