models/topic.py
import time
from models import Model
from models.user import User
from models.mongua import Mongua
import json
import logging
ogger = logging.getLogger("bbs")


class Topic(Model):
    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def __init__(self, form):
        self.id = None
        self.views = 0
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.ct = int(time.time())
        self.ut = self.ct
        self.user_id = form.get('user_id', '')
        self.board_id = int(form.get('board_id', -1))
        self.istop = False
        self.last_time = None

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

    def set_time(self):
        self.last_time = int(time.time())
        self.save()

    @staticmethod
    def top():
        m = Topic.find_all(istop=True)
        return m

    @staticmethod
    def notop():
        m = Topic.find_all(istop=False)
        return m


class Cache(object):
    def get(self, key):
        pass

    def set(self, key, value):
        pass


class MemoryCache(Cache):
    def __init__(self):
        self.cache = {}

    def get(self, key):
        return self.cache[key]

    def set(self, key, value):
        self.cache[key] = value


class RedisCache(Cache):
    import redis
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def set(self, key, value):
        return RedisCache.redis_db.set(key, value)

    def get(self, key):
        return RedisCache.redis_db.get(key)


class Topic(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('content', str, ''),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('views', int, 0),
        ('istop', bool, False),
        ('last_time', int, None),
        ('title', str, ''),
        ('last_reply_id', str, None)
    ]
    should_update_all = True
    # 1. memory cache
    cache = MemoryCache()
    # 2. redis cahce
    redis_cache = RedisCache()

    def to_json(self):
        d = dict()
        for k in Topic.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self, key)
        return json.dumps(d)

    @classmethod
    def from_json(cls, j):
        d = json.loads(j)

        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        # time.sleep(3)
        # return Topic.all()
        return Topic.notop()

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def save(self):
        super(Topic, self).save()
        Topic.should_update_all = True

    @classmethod
    def cache_all(cls):

        # 2. redis cache
        if Topic.should_update_all:
            Topic.redis_cache.set('topic_all', json.dumps([i.to_json() for i in cls.all_delay()]))
            Topic.should_update_all = False
        j = json.loads(Topic.redis_cache.get('topic_all').decode('utf-8'))
        j = [Topic.from_json(i) for i in j]
        return j

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id=self.user_id)
        return u

    @staticmethod
    def top():
        m = Topic.find_all(istop=True)
        return m

    @staticmethod
    def notop():
        m = Topic.find_all(istop=False)
        return m

    def set_time(self):
        self.last_time = int(time.time())
        self.save()

    def last_replier(self):
        from .user import User
        u = User.find(self.last_reply_id)
        return u

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)

from werkzeug.utils import secure_filename
from models.user import User
from config import user_file_director
import os
from routes import *

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/logout")
def log_out():
    u = current_user()
    if u is None:
        return redirect(url_for(".index"))
    session.pop("user_id")
    return redirect(url_for(".index"))


@main.route("/")
def index():
    u = current_user()
    # print(123)
    # log(123333)
    # logger.debug('just do it')
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        # print('session before', session)
        session['user_id'] = u.id
        # print('session after', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# @main.route('/profile')
# def profile():
#     u = current_user()
#     if u is None:
#         return redirect(url_for('.index'))
#     else:
#         return render_template('profile.html', user=u)


def allow_file(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_file_type
    return suffix in accept_user_file_type


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".profile"))

    if 'file' not in request.files:
        # return redirect(request.url)
        abort(500)

    file = request.files['file']
    if file.filename == '':
        abort(500)
        # return redirect(url_for(".profile"))

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))  # 路径拼接
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    if filename is None:
        return ''
    return send_from_directory(user_file_director, filename)


@main.route('/setting')
def setting():
    # print(2333)
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('setting.html', user=u)


@main.route('/setpass', methods=["POST"])
def setpass():
    u = current_user()
    oldpass = request.form.get('old_pass', '')
    if u is not None and u.password == u.salted_password(oldpass):
        pwd = request.form.get('new_pass')
        u.password = u.salted_password(pwd)
        u.save()
        return redirect(url_for('.setting'))
    else:
        abort(403)

routes/mail.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
from models.mail import Mail


main = Blueprint('mail', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    mail = Mail.new(form)
    # 为了安全
    mail.set_sender(current_user().id)
    mail.set_receiver(mail.receiver_name)
    return redirect(url_for(".index"))


@main.route("/", methods=["GET"])
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    send_mail = Mail.find_all(sender_id=u.id)
    received_mail = Mail.find_all(receiver_id=u.id)

    return render_template("mail/index.html", sends=send_mail, receives=received_mail)


@main.route("/view/<int:id>")
def view(id):
    mail = Mail.find(id)
    # 不是你自己手法的，你肯定不能看
    # 不是收的人，那你看了也不会变成已读
    u = current_user()
    if current_user().id == mail.receiver_id:
        mail.mark_read()
    if current_user().id in [mail.receiver_id, mail.sender_id]:
        return render_template("mail/detail.html", mail=mail, user=u)
    else:
        return redirect(url_for(".index"))


@main.route('/<username>')
def setting(username):
    u = current_user()
    return render_template("mail/setting.html", user=u)

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply
from models.topic import Topic


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    form = request.form
    m = Reply.new(form, user_id=u.id)
    topic_id = m.topic_id
    topic = Topic.find_by(id=topic_id)
    topic.last_reply_id = u.id
    topic.set_time()
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board


main = Blueprint('topic', __name__)


import uuid
csrf_tokens = dict()


@main.route("/")
def index(num=100):
    # board_id = 2
    # 实现了分页的功能，前端页面暂时没有处理
    # print(123)
    start = int(request.args.get('start', 0))
    ms1 = []
    ms2 = []
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms1 = Topic.top()
        ms2 = Topic.cache_all()

    else:
        ms = Topic.find_all(board_id=board_id)
        for m in ms:
            if m.istop==True:
                ms1.append(m)
            else:
                ms2.append(m)
    token = str(uuid.uuid4())
    u = current_user()
    # print(u.role)
    # print(u.username)
    if u is not None:
        csrf_tokens[token] = u.id
    bs = Board.all()
    num -= len(ms1)
    start -= num
    if start < 0:
        start = 0
    if u is None:
        return render_template("topic/index1.html", ms1=ms1, ms2=ms2, token=token, bs=bs, start=start, num=num)
    return render_template("topic/index.html", ms1=ms1, ms2=ms2, token=token, bs=bs, start=start, num=num, user=u)


@main.route('/<int:id>')
def detail(id):
    from models.user import User
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    user_id = m.user_id
    username = User.get(user_id).username
    u = User.get(user_id)
    return render_template("topic/detail.html", topic=m, username=username, user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    topic = Topic.get(id)
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if u.role == 1:
        if token in csrf_tokens and csrf_tokens[token] == u.id:
            csrf_tokens.pop(token)
            if u is not None:
                # print('删除 topic 用户是', u, id)
                Topic.delete(id)
                # topic.delete()
                return redirect(url_for('.admin'))
            else:
                abort(404)
        else:
            abort(403)
    else:
        return redirect(url_for('.index'))


@main.route("/new")
def new():
    u = current_user()
    if u is None:
        return redirect("/")
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)


@main.route("/admin")
def admin():
    if current_user().role != 1:
        return redirect(url_for('index.index'))
    ms1 = []
    ms2 = []
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms1 = Topic.top()
        ms2 = Topic.cache_all()

    else:
        ms = Topic.find_all(board_id=board_id)
        for m in ms:
            if m.istop == True:
                ms1.append(m)
            else:
                ms2.append(m)
    token = str(uuid.uuid4())
    u = current_user()
    if u is not None:
        csrf_tokens[token] = u.id
    bs = Board.all()
    return render_template("topic/admin.html", ms1=ms1, ms2=ms2, token=token, bs=bs)


@main.route("/settop/<int:id>")
def settop(id):
    m = Topic.get(id)
    m.istop = True
    m.save()
    return redirect(url_for('.admin'))


@main.route("/setnotop/<int:id>")
def setnotop(id):
    m = Topic.get(id)
    m.istop = False
    m.save()
    return redirect(url_for('.admin'))

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply
from models.topic import Topic
from models.topic import User


main = Blueprint('user', __name__)


@main.route("/<username>")
def detail(username):
    # u = current_user()
    u = User.find_by(username=username)
    ts = Topic.find_all(user_id=u.id)
    tss = []
    rs = Reply.find_all(user_id=u.id)
    for r in rs:
        t = Topic.find_by(id=r.topic_id)
        if t is not None and t.user_id != u.id:
            tss.append(t)
    return render_template("user/detail.html", user=u, ts=ts, tss=tss)


@main.route('/update', methods=['POST'])
def update():
    u = current_user()
    form = request.form
    u.update(form)
    return redirect(url_for('index.setting'))

templates/topic/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs admin</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <h1>{{ user().username }}</h1>
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">

                    {% for t in ms1 %}
                    <div class="cell">
                        <a class='last_time pull-right'>
                             <span class="last_active_time">{{ t.last_time | delta }}</span>
                         </a>
                        <div class="topic_title_wrapper">
                            <a class="user_avatar pull-left">
                                 <!--<img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}-->
                            <!--title="atian25"/>-->
                                <img src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>

                            </a>
                            <!--{% if name and name == 'admin' %}-->
                            <!--{% else %}-->
                            <!--{% endif %}-->
                            <span class='put_good'>置顶</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>
                            <a  href="{{ url_for('topic.setnotop', id=t.id) }}">
                                取消置顶
                            </a>

                        </div>
                    </div>
                    {% endfor %}

                    {% for t in ms2 %}
                    <div class="cell">
                        <a class='last_time pull-right'>
                             <span class="last_active_time">{{ t.last_time | delta }}</span>
                         </a>
                        <div class="topic_title_wrapper">
                            <a class="user_avatar pull-left">
                                 <!--<img src={{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}-->
                            <!--title="atian25"/>-->
                                <img src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>

                            </a>
                            <span class='topiclist-tab'>{{ t.board().title }}</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>
                             <a  href="{{ url_for('topic.settop', id=t.id) }}">
                                置顶
                            </a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!--<div class="paginator">-->
        <!--<span class="prev">-->
            <!--&lt;前页-->
        <!--</span>-->



                <!--<span class="thispage">1</span>-->

            <!--<a href="?start=25&amp;filter=" >2</a>-->


            <!--<a href="?start=50&amp;filter=" >3</a>-->


            <!--<a href="?start=75&amp;filter=" >4</a>-->


            <!--<a href="?start=100&amp;filter=" >5</a>-->


            <!--<a href="?start=125&amp;filter=" >6</a>-->


            <!--<a href="?start=150&amp;filter=" >7</a>-->


            <!--<a href="?start=175&amp;filter=" >8</a>-->


            <!--<a href="?start=200&amp;filter=" >9</a>-->


            <!--<a href="?start=225&amp;filter=" >10</a>-->

        <!--<span class="next">-->
            <!--<link rel="next" href="?start=25&amp;filter="/>-->
            <!--<a href="?start=25&amp;filter=" >后页&gt;</a>-->
        <!--</span>-->

            <!--<span class="count">(共250条)</span>-->
        <!--</div>-->
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>
</body>
</html>

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
{% extends "base.html"%}
<div id="main">
    <!--<h1>{{ user.username }}</h1>-->
    {% block sidebar %}
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">作者信息</span>
                </div>
                <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.username }}">
                            <img src={{ url_for('index.uploads', filename=user.user_image, v=3, s=120) }}>
                        </a>
                        <span class="user_name"><a class="dark" href="/user/{{ user.username }}">{{ user.username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.note }}
                        </span>
                    </div>
                </div>
            </div>
            </div>
            <!--<div class="panel">-->
                    <!--<div class="inner">-->
                        <!--<a href="/topic/new" class="create_topic_btn">-->
                            <!--<span class="span-success">发布话题</span>-->
                        <!--</a>-->
                    <!--</div>-->
                <!--</div>-->
        </div>
    {% endblock %}

    {% block content %}
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.ct | delta }}
            </span>
                    <span>
                作者
                {{  username }}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 <a href="{{ url_for('topic.index', board_id=topic.board_id) }}">
                {{ topic.board().title }}
                    </a>
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ markdown(topic.content) | safe }}
                        <!--{{ topic.content }}-->
                    </div>
                </div>
            </div>
        </div>
        <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a href={{ url_for('user.detail', username=r.user().username) }} class="user_avatar" >
                    <img src={{ url_for('index.uploads', filename=r.user().user_image, v=3, s=120) }}>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ r.user().username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 • {{ r.ct | delta }}
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">
                    {{ markdown(r.content, output_format = 'html') | safe }}
                    <!--{{ r.content }}-->
                </div>
            </div>
        </div>
        {% endfor %}

            <div class="panel">
    <div class="header">
      <span class="col_fade">添加回复</span>
    </div>
    <div class="inner reply">
      <form id="reply_form" action={{ url_for('reply.add') }} method="post">

        <div class="markdown_editor in_editor">
          <div class="markdown_in_editor">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea class="editor" name="content" rows="8" ></textarea>
              <!--<div class="editor-toolbar"><a class="eicon-bold"></a><a class="eicon-italic"></a><i class="separator">|</i><a class="eicon-quote"></a><a class="eicon-unordered-list"></a><a class="eicon-ordered-list"></a><i class="separator">|</i><a class="eicon-link"></a><a class="eicon-image"></a><i class="separator">|</i><a class="eicon-info" href="http://lab.lepture.com/editor/markdown" target="_blank"></a><a class="eicon-preview"></a><a class="eicon-fullscreen"></a></div><div class="CodeMirror cm-s-paper"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 9px; left: 4px;"><textarea autocorrect="off" autocapitalize="off" spellcheck="false" tabindex="0" style="position: absolute; padding: 0px; width: 1000px; height: 1em; outline: none; font-size: 4px;"></textarea></div><div class="CodeMirror-hscrollbar" style="left: 0px;"><div style="height: 1px;"></div></div><div class="CodeMirror-vscrollbar"><div style="width: 1px;"></div></div><div class="CodeMirror-scrollbar-filler"></div><div class="CodeMirror-gutter-filler"></div><div class="CodeMirror-scroll" tabindex="-1"><div class="CodeMirror-sizer" style="min-width: 41px; margin-left: 0px; min-height: 36px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines"><div style="position: relative; outline: none;"><div class="CodeMirror-measure"><pre><span>​</span></pre></div><div style="position: relative; z-index: 1; display: none;"></div><div class="CodeMirror-code"><pre>&nbsp;</pre></div><div class="CodeMirror-cursor" style="left: 4px; top: 5px; height: 17px;">&nbsp;</div><div class="CodeMirror-cursor CodeMirror-secondarycursor" style="display: none;">&nbsp;</div></div></div></div></div><div style="position: absolute; height: 30px; width: 1px; top: 36px;"></div><div class="CodeMirror-gutters" style="display: none; height: 160px;"></div></div></div>-->

            <div class="editor_buttons">
              <input class="span-primary submit_btn" type="submit" data-loading-text="回复中.." value="回复">
            </div>
          </div>

        </div>

        <!--<input type="hidden" name="_csrf" id="_csrf" value="p6cfr6qO-1-reJ37ydb2ituHj3mH64w-pUnc">-->
      </form>
    </div>
  </div>

        <!--<div>-->
            <!--<form action="{{ url_for('reply.add') }}" method="post">-->
                <!--<input type="hidden" name="topic_id" value="{{ topic.id }}">-->
                <!--<textarea name="content"></textarea>-->
                <!--<button>添加回复</button>-->
            <!--</form>-->
        <!--</div>-->
        </div>

    </div>

        {% endblock %}


</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <h1>{{ user().username }}</h1>
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>