models/user.py
from models import Model
from models.mongua import Mongua


class User(Model):
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """
    def __init__(self, form):
        self.id = form.get('id', None)
        self.username = form.get('username', '')
        self.password = form.get('password', '')
        self.role = 11
        self.user_image = 'default.png'

    def is_admin(self):
        return self.role == 1

    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()
        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        u = User(form)
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None


class User(Mongua):
    __fields__ = Mongua.__fields__ + [
        ('username', str, ''),
        ('password', str, ''),
        ('user_image', str, 'default.png'),
        ('role', int, 11),
        ('location', str, ''),
        ('email', str, ''),
        ('note', str, '这家伙很懒，什么个性签名都没有留下。'),
    ]

    """
        User 是一个保存用户数据的 model
        现在只有两个属性 username 和 password
        """
    # def __init__(self):
    #     self.user_image = 'default.png'

    # def from_form(self, form):
    #     self.id = form.get('id', None)
    #     self.username = form.get('username', '')
    #     self.password = form.get('password', '')
    #     self.user_image = 'default.png'

    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) > 2 and User.find_by(username=name) is None:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        u = User()
        u.username = form.get("username", '')
        u.password = form.get("password", "")
        user = User.find_by(username=u.username)
        if user is not None and user.password == u.salted_password(u.password):
            return user
        else:
            return None

    def is_admin(self):
        return self.role == 1

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)

from werkzeug.utils import secure_filename
from models.user import User
from config import user_file_director
import os
from routes import *

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/logout")
def log_out():
    u = current_user()
    if u is None:
        return redirect(url_for(".index"))
    session.pop("user_id")
    return redirect(url_for(".index"))


@main.route("/")
def index():
    u = current_user()
    # print(123)
    # log(123333)
    # logger.debug('just do it')
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        # print('session before', session)
        session['user_id'] = u.id
        # print('session after', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


# @main.route('/profile')
# def profile():
#     u = current_user()
#     if u is None:
#         return redirect(url_for('.index'))
#     else:
#         return render_template('profile.html', user=u)


def allow_file(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_file_type
    return suffix in accept_user_file_type


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".profile"))

    if 'file' not in request.files:
        # return redirect(request.url)
        abort(500)

    file = request.files['file']
    if file.filename == '':
        abort(500)
        # return redirect(url_for(".profile"))

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))  # 路径拼接
        u.user_image = filename
        u.save()

    return redirect(url_for(".setting"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    if filename is None:
        return ''
    return send_from_directory(user_file_director, filename)


@main.route('/setting')
def setting():
    # print(2333)
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('setting.html', user=u)


@main.route('/setpass', methods=["POST"])
def setpass():
    u = current_user()
    oldpass = request.form.get('old_pass', '')
    if u is not None and u.password == u.salted_password(oldpass):
        pwd = request.form.get('new_pass')
        u.password = u.salted_password(pwd)
        u.save()
        return redirect(url_for('.setting'))
    else:
        abort(403)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *

from models.topic import Topic
from models.board import Board


main = Blueprint('topic', __name__)


import uuid
csrf_tokens = dict()


@main.route("/")
def index(num=100):
    # board_id = 2
    # 实现了分页的功能，前端页面暂时没有处理
    # print(123)
    start = int(request.args.get('start', 0))
    ms1 = []
    ms2 = []
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms1 = Topic.top()
        ms2 = Topic.cache_all()

    else:
        ms = Topic.find_all(board_id=board_id)
        for m in ms:
            if m.istop==True:
                ms1.append(m)
            else:
                ms2.append(m)
    token = str(uuid.uuid4())
    u = current_user()
    # print(u.role)
    # print(u.username)
    if u is not None:
        csrf_tokens[token] = u.id
    bs = Board.all()
    num -= len(ms1)
    start -= num
    if start < 0:
        start = 0
    if u is None:
        return render_template("topic/index1.html", ms1=ms1, ms2=ms2, token=token, bs=bs, start=start, num=num)
    return render_template("topic/index.html", ms1=ms1, ms2=ms2, token=token, bs=bs, start=start, num=num, user=u)


@main.route('/<int:id>')
def detail(id):
    from models.user import User
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    user_id = m.user_id
    username = User.get(user_id).username
    u = User.get(user_id)
    return render_template("topic/detail.html", topic=m, username=username, user=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    topic = Topic.get(id)
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if u.role == 1:
        if token in csrf_tokens and csrf_tokens[token] == u.id:
            csrf_tokens.pop(token)
            if u is not None:
                # print('删除 topic 用户是', u, id)
                Topic.delete(id)
                # topic.delete()
                return redirect(url_for('.admin'))
            else:
                abort(404)
        else:
            abort(403)
    else:
        return redirect(url_for('.index'))


@main.route("/new")
def new():
    u = current_user()
    if u is None:
        return redirect("/")
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)


@main.route("/admin")
def admin():
    if current_user().role != 1:
        return redirect(url_for('index.index'))
    ms1 = []
    ms2 = []
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        # ms = Topic.all()
        ms1 = Topic.top()
        ms2 = Topic.cache_all()

    else:
        ms = Topic.find_all(board_id=board_id)
        for m in ms:
            if m.istop == True:
                ms1.append(m)
            else:
                ms2.append(m)
    token = str(uuid.uuid4())
    u = current_user()
    if u is not None:
        csrf_tokens[token] = u.id
    bs = Board.all()
    return render_template("topic/admin.html", ms1=ms1, ms2=ms2, token=token, bs=bs)


@main.route("/settop/<int:id>")
def settop(id):
    m = Topic.get(id)
    m.istop = True
    m.save()
    return redirect(url_for('.admin'))


@main.route("/setnotop/<int:id>")
def setnotop(id):
    m = Topic.get(id)
    m.istop = False
    m.save()
    return redirect(url_for('.admin'))

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply
from models.topic import Topic
from models.topic import User


main = Blueprint('user', __name__)


@main.route("/<username>")
def detail(username):
    # u = current_user()
    u = User.find_by(username=username)
    ts = Topic.find_all(user_id=u.id)
    tss = []
    rs = Reply.find_all(user_id=u.id)
    for r in rs:
        t = Topic.find_by(id=r.topic_id)
        if t is not None and t.user_id != u.id:
            tss.append(t)
    return render_template("user/detail.html", user=u, ts=ts, tss=tss)


@main.route('/update', methods=['POST'])
def update():
    u = current_user()
    form = request.form
    u.update(form)
    return redirect(url_for('index.setting'))

templates/user/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人主页</title>
</head>
<body>
{% extends "base.html"%}
<div id="main">
  {% block content %}
    <div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href={{ url_for('topic.index') }}>主页</a><span class="divider">/</span></li>
      </ul>
    </div>
    <div class="inner userinfo">
      <div class="user_big_avatar">
          <img src={{ url_for('index.uploads', filename=user.user_image, v=3, s=120) }}>
      </div>
      <span class="user_name"><a class="dark">{{ user.username }}</a></span>


      <div class="user_profile">
                    <ul class="unstyled">
                        <span class="big">0</span> 积分
                        <li>
                            <i class="fa fa-lg fa-fw fa-home"></i>
                            <a class="dark">
                                邮件：{{ user.address }}
                            </a>
                        </li>
                        <li>
                            <i class="fa fa-lg fa-fw fa-github"></i>
                            <a class="dark">
                                地点：{{ user.location }}
                            </a>
                        </li>
                        <li>
                            <i class="fa fa-lg fa-fw fa-github"></i>
                            <a class="dark">
                                个性签名：{{ user.note }}
                            </a>
                        </li>
                    </ul>
                </div>
      <p class="col_fade">注册时间 {{ user.ct | delta }} </p>

    </div>
  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近创建的话题</span>
        {% for t in ts %}
                    <div class='cell'>

                        <a class="user_avatar pull-left" href={{ url_for("user.detail", username=t.user().username) }}>
                        <img src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title='点击数'>
                                {{ t.views }}
                            </span>
                        </span>

                        <a class='last_time pull-right'>
                            <!--<img class="user_small_avatar" src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>-->
                            <span class="last_active_time">{{ t.last_time | delta }}</span>
                        </a>


                        <div class="topic_title_wrapper">


                            <span class='topiclist-tab'>{{ t.board().title }}</span>


                            <a class='topic_title' href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
        {% endfor %}
    </div>

    <!--<div class="inner">-->
      <!--<p>无话题</p>-->
    <!--</div>-->

  </div>

  <div class="panel">
    <div class="header">
      <span class="col_fade">最近参与的话题</span>
        {% for t in tss %}
                    <div class='cell'>

                        <a class="user_avatar pull-left" href={{ url_for("user.detail", username=t.user().username) }}>
                        <img src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title='点击数'>
                                {{ t.views }}
                            </span>
                        </span>

                        <a class='last_time pull-right'>
                            <!--<img class="user_small_avatar" src={{ url_for('index.uploads', filename=t.user().user_image, v=3, s=120) }}>-->
                            <span class="last_active_time">{{ t.last_time | delta }}</span>
                        </a>


                        <div class="topic_title_wrapper">


                            <span class='topiclist-tab'>{{ t.board().title }}</span>


                            <a class='topic_title' href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
        {% endfor %}
    </div>

    <!--<div class="inner">-->
      <!--<p>无话题</p>-->
    <!--</div>-->

  </div>
    </div>
</div>
  {% endblock %}



</body>
</html>